### ISSUE TITLE
Please rename github project and module names

### ISSUE THREAD

**Issue by snicoll** [olmero/rollbar-spring-boot-starter#4]
As [defined in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) we prefer third party starters do not start with `spring-boot`. For consistency, I'd argue that the project name should be renamed as well.

`rollbar-spring-boot-starter` would be the name I am expecting.

Thanks!

**Comment by pkaufi** [comment]
I'll look into that

**Comment by pkaufi** [comment]
@snicoll I just did the renaming (and some of your proposed changes) and released a new version. There are still some things unclear about the GitProperties (https://github.com/olmero/rollbar-spring-boot-starter/issues/6), but I'll write it in that issue. I hope those changes are as you expected them to be and the starter can be added to the third party list you mentioned

**Comment by snicoll** [comment]
Thanks a lot, that looks good to me. I think we can close this one as far as I am concerned.

**Comment by pkaufi** [comment]
Thank you for your valuable feedback and contribution. closing this now
