### ISSUE TITLE
Metadata exposes a `git-properties` property

### ISSUE THREAD

**Issue by snicoll** [olmero/rollbar-spring-boot-starter#6]
It looks like you're trying to inject `GitProperties` in `RollbarProperties`. The `@Autowired` trickery is not required as Spring Framework uses the constructor by default already (as long as there is one candidate).

Also, the getter is exposed publicly which means a useless `git-properties` is exposed (check the metadata in `target/classes`.

The best practice is to delegate that code outside of the properties object, i.e. let it `return null` and have the logic to fallback on `GitProperties` in a service that's calling it. It makes it also more obvious if the user has configured something or not (right now it's hidden behind the current getter).

**Comment by pkaufi** [comment]
@snicoll is https://github.com/olmero/rollbar-spring-boot-starter/pull/12 what you had in mind?
